run:
	docker compose up -d

build:
	docker compose up --build

stop:
	docker compose stop

restart:
	docker compose restart

log:
	docker compose logs -f

clean:
	docker compose down -v
